### ISSUE TITLE
Documentation down

### ISSUE THREAD

**Issue by nrstillman** [sandialabs/compadre#249]
Hi all, 

Looks like your documentation page is linked incorrectly. I think the correct url should be: 

https://sandialabs.github.io/compadre/index.html

Thanks

NS

**Comment by kuberry** [comment]
Hi @nrstillman. Thank you for pointing this out. We recently changed organizations from SNLComputation to sandialabs on github.com, so this is very possible. Can you point me to the page or document that referenced the old documentation link?

**Comment by nrstillman** [comment]
Apologies, should have added that in. 

It's in the README.md

**Comment by kuberry** [comment]
Thanks @nrstillman. Just updated that. You should see it in the README.md on the master branch.
